# Generated by Django 6.0.3 on 2026-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodaram_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Activity cover image', upload_to='activities/')),
                ('duration', models.CharField(blank=True, help_text='Duration (e.g., 3 Days, 2 Hours)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
