# Generated by Django 6.0.3 on 2026-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodaram_app', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='camping/')),
                ('check_in', models.CharField(max_length=20)),
                ('check_out', models.CharField(max_length=20)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_person_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_items', models.TextField()),
                ('facilities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Camping Packages',
            },
        ),
    ]
