# Generated by Django 6.0.3 on 2026-03-08 08:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodaram_app', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='check_in',
        ),
        migrations.AddField(
            model_name='booking',
            name='camping_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='koodaram_app.campingpackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=datetime.datetime(2026, 3, 8, 8, 52, 8, 101665, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
