# Generated by Django 6.0.3 on 2026-04-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koodaram_app', '0005_rename_date_booking_check_in_booking_camping_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campingpackage',
            name='extra_person_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campingpackage',
            name='normal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campingpackage',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
