# Generated by Django 6.0.3 on 2026-04-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koodaram_app', '0006_alter_campingpackage_extra_person_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campingpackage',
            name='extra_person_price',
        ),
    ]
